### PR TITLE
Cleaner evolution.

### PR DESCRIPTION
**Pull request by dkorolev**
Hi Max,

One small step one giant leap -- eliminated extra template parameters in default and bolierplate evolutors, and resorted to:

* `CURRENT_STRUCT_EVOLVER`, with
  * `CURRENT_COPY_FIELD`, and
  * `CURRENT_COPY_SUPER`, plus
* `CURRENT_VARIANT_EVOLVER`, with
  * `CURRENT_COPY_CASE`, and
  * `CURRENT_EVOLVE_CASE`.

CC @nyospe -- we'll be needing this shortly.

Thanks,
Dima

### CODE REVIEW

**Comment by mzhurovich** [comment]
@dkorolev LGTM! Couple of questions:
1) Do we need `CURRENT_TYPE_EVOLVER_NATURAL_VARIANT_CASE` macro?
2) What do you think about `CURRENT_DROP_{FIELD/CASE}`?

**Comment by dkorolev** [comment]
@mzhurovich, `CURRENT_TYPE_EVOLVER_NATURAL_VARIANT_CASE` is for backwards compatibility, and will be removed shortly. `CURRENT_DROP_FIELD` is unnecessary, and `CURRENT_DROP_CASE` is a great idea, gimme a second.

**Comment by dkorolev** [comment]
@mzhurovich PTAL

**Comment by mzhurovich** [comment]
`CURRENT_DROP_FIELD` can be no-op, just for increasing readability and consistency.

**Comment by mzhurovich** [comment]
Merging anyway.

**Pull request merged**
