### PR TITLE
Karl visualization.

### PR DESCRIPTION
**Pull request by dkorolev**
Hi Max,

This tiny piece is all we need for **SLAUGHTER**!

Thanks,
Dima

### CODE REVIEW

**Comment by dkorolev** [comment]
karl

It's fleet browsability, Karl!

**Comment by sompylasar** [comment]
Wow!

**Comment by dkorolev** [comment]
It's in prod btw!

**Comment by mzhurovich** [comment]
Prospimsya - pochitaem!

**Comment by dkorolev** [comment]
:beers:

**Pull request merged**
