### PR TITLE
Checking whether `IntrusiveClient` for `WaitableAtomic` is in use at all except the test.

### PR DESCRIPTION
**Pull request by dkorolev**
@mzhurovich I'm strongly considering removing it, since `Owned<>`/`Borrowed<>` (or the good old `shared_ptr<>`) appear to offer a cleaner way than this confusing intrusive thingy.

### CODE REVIEW

**Comment by dkorolev** [comment]
(Of course, if the tests pass, I'll clean up the smoke test to actually run the test, just in a non-intrusive way.)

**Comment by dkorolev** [comment]
Okay, seems to work, minor tweaks now ...

**Comment by dkorolev** [comment]
@mzhurovich -- good to review per commit!

**Comment by mzhurovich** [comment]
Agree, I'm all for cleanness and simplicity, and intrusive pointers are pretty niche thing, so I don't think we lose anything by removing this implementation here. LGTM.

**Pull request merged**
