### PR TITLE
Fixed datetime parsing.

### PR DESCRIPTION
**Pull request by mzhurovich**
@grixa Thanks for finding a bug!

### CODE REVIEW

**Comment by dkorolev** [comment]
LGTM!!!

**Comment by grixa** [comment]
Wow, I didn't think about it.
But it looks like it doesn't help in some cases.

**Comment by grixa** [comment]
Sorry, it really helps, I just didn't rebuild the second test :)
LGTM!

**Comment by dkorolev** [comment]
```
dima@dima-x1:~/github/dkorolev/TEST $ cat 1.cc 
#include "../Current/Bricks/time/chrono.h"
#include <iostream>

std::chrono::microseconds ParseDateTime(const std::string& value) {
  std::tm tm;
  std::chrono::microseconds ret(0);
  if (strptime(value.c_str(), "%d %b %Y", &tm)) {
    tm.tm_isdst = 0;
    ret = std::chrono::time_point_cast<std::chrono::microseconds>(std::chrono::system_clock::from_time_t(timegm(&tm)))
              .time_since_epoch();
  }
  auto ret2 = current::UTCDateTimeStringToTimestamp(value, "%d %b %Y");
  std::cout << value << " -> " << ret.count() << " -> " << ret2.count() << std::endl;
  std::cout << current::FormatDateTime<current::time::TimeRepresentation::UTC>(ret, "%d %b %Y") << " -> "
            << current::FormatDateTime<current::time::TimeRepresentation::UTC>(ret2, "%d %b %Y") << std::endl;
  return ret;
}

int main() {
  ParseDateTime("15 Dec 1995");
  ParseDateTime("15 Dec 1995");
  ParseDateTime("15 Dec 1995");
  ParseDateTime("15 Dec 1995");

  return 0;
}
```

image

```
dima@dima-x1:~/github/dkorolev/TEST $ make
if [ -f test.cc ] ; then \
	make test ;\
else \
	find .current/ -perm /111 -type f -exec "{}" ";" ; \
fi
15 Dec 1995 -> -3084999803516579 -> -4229743825709551
28 Mar 1872 -> 19 Dec 1835
15 Dec 1995 -> 819035432000000 -> -4229743825709551
15 Dec 1995 -> 19 Dec 1835
15 Dec 1995 -> 819035432000000 -> -4229743825709551
15 Dec 1995 -> 19 Dec 1835
15 Dec 1995 -> 819035432000000 -> -4229743825709551
15 Dec 1995 -> 19 Dec 1835
```

image

```
dima@dima-x1:~/github/dkorolev/TEST $ touch 1.cc 
dima@dima-x1:~/github/dkorolev/TEST $ make
g++ -std=c++11 -Wall -Wno-strict-aliasing -W   -ftemplate-backtrace-limit=0  -ftemplate-depth=10000 -o ".current/1" "1.cc" -pthread -ldl
if [ -f test.cc ] ; then \
	make test ;\
else \
	find .current/ -perm /111 -type f -exec "{}" ";" ; \
fi
15 Dec 1995 -> 8944125542890823 -> 818985600000000
05 Jun 2253 -> 15 Dec 1995
15 Dec 1995 -> 819006576000000 -> 818985600000000
15 Dec 1995 -> 15 Dec 1995
15 Dec 1995 -> 819006576000000 -> 818985600000000
15 Dec 1995 -> 15 Dec 1995
15 Dec 1995 -> 819006576000000 -> 818985600000000
15 Dec 1995 -> 15 Dec 1995
```

**Pull request merged**
