### PR TITLE
TypeSystem fix to allow base struct belong to different namespace.

### PR DESCRIPTION
**Pull request by mzhurovich**
@dkorolev Looks like I fixed dat shit. 
For now, it's common base class constructor call syntax - ` : SUPER(...)`

### CODE REVIEW

**Comment by dkorolev** [comment]
Thanks! Will look from a laptop tonight.

PS: Previously, I could make SUPER()-based initialization work, but not in
Windows :-( Could you try it pls?

On Tuesday, December 29, 2015, Maxim Zhurovich <notifications@github.com>
wrote:

> Assigned #331 <https://github.com/c5t/Current/pull/331> to @dkorolev
> <https://github.com/dkorolev>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/c5t/Current/pull/331#event-502466344>.
>


-- 
And, as always, have a nice day!
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Comment by dkorolev** [comment]
Hi @mzhurovich ,

Looked at `CURRENT_STRUCT`-related changes. Cool! I had a feeling adding `CURRENT_REFLECTION_HELPER<s>` to the template arguments list of `CURRENT_STRUCT_HELPERS` could work -- glad to see you made it!

I assume you tried it on Windows as well. LGTM++, and feel free to click "Merge" if this assumption is right.

Thanks!
Dima

PS: `TypeSystem` tests pass with both `g++` and `clang++` on my laptop.

**Comment by mzhurovich** [comment]
@dkorolev Just had an opportunity to test it in VS2015 and realized that I forgot one line :)
All TypeSystem tests pass except for one which reads golden files (I assume because of symlinks).

**Comment by dkorolev** [comment]
@mzhurovich Yay! Thank you!

(That test failure reason: Yes, golden file path, plus Windows line endings. In production with it!)

**Pull request merged**
