### PR TITLE
Top-level `make`, `make test` and `make check` and renamed `Bricks/3party` into `3rdparty`.

### PR DESCRIPTION
**Pull request by dkorolev**
It's not as scary as it looks.

Known issues: 

* `gnuplot` still fails on Mac.
* coverage report generation -- at least on my Mac it's not configured.

@mzhurovich : PTAL.
@sompylasar : FYI.

Thanks!
Dima

### CODE REVIEW

**Comment by dkorolev** [comment]
And I'm happy to report that, surprisingly, no new issues have been uncovered on Mac, aside from changing the default Irises port.

Thanks,
Dima

**Comment by dkorolev** [comment]
@mzhurovich : Thanks for the review, done, PTAL.

**Comment by dkorolev** [comment]
Will add `#ifdef _MSC_VER` -> `#pragma warning`.

After https://github.com/c5t/Current/pull/205.

**Comment by dkorolev** [comment]
@mzhurovich : Ready for your review!

I didn't test it on Windows yet ... long story, will do tomorrow.

Thanks,
Dima

**Comment by dkorolev** [comment]
That was a nontrivial one to catch!

```
dima@Users-MacBook-Pro /Users/dima/github/dkorolev/Current/Sherlock/yoda (master) $ make check
/Users/dima/Documents/github/dkorolev/Current/scripts/check-headers.sh
Testing all headers to comply with the header-only paradigm.
Directory: .
Compiling: metaprogramming.h sfinae.h clang: warning: -framework Foundation: 'linker' input unused
/Users/dima/github/dkorolev/Current/Sherlock/yoda/.current/headers/sfinae.h.g++.cc:158:3: error: static_assert failed "The key type defines neither `Hash()` nor `operator<()`."
  static_assert(HasOperatorLess<T_KEY>(0), "The key type defines neither `Hash()` nor `operator<()`.");
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dima/github/dkorolev/Current/Sherlock/yoda/.current/headers/sfinae.h.g++.cc:163:1: note: in instantiation of template class 'yoda::sfinae::T_MAP_TYPE_SELECTOR<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, false, false>' requested here
using T_MAP_TYPE =
^
/Users/dima/github/dkorolev/Current/Sherlock/yoda/.current/headers/sfinae.h.g++.cc:172:66: note: in instantiation of template type alias 'T_MAP_TYPE' requested here
static_assert(std::is_same<std::unordered_map<std::string, int>, T_MAP_TYPE<std::string, int>>::value, "");
                                                                 ^
1 error generated.
Terminating.
make: *** [check] Error 1
```

**Comment by mzhurovich** [comment]
@dkorolev Suggestion: rename `zzz_full_test` into something like `.current_full_test`. What do you think?

**Comment by dkorolev** [comment]
@mzhurovich , all taken care of.

Regarding the `zzz_full_test` -- let me rethink it when I not only get to a Windows machine, but get to a Windows machine with Visual Studio installed and running (*). My goal is to have the tests pass from Visual Studio without having to run any shell scripts.

(*) http://dimakorolev.quora.com/Windows-Again

**Comment by mzhurovich** [comment]
@dkorolev Deal! ;)
LGTM++! Merging.

**Comment by dkorolev** [comment]
Yay! Thank you!

I'll be available for the call in 20 minutes.

**Pull request merged**
