### PR TITLE
Fixes for issues that came up in Win32 build

### PR DESCRIPTION
**Pull request by nyospe**

### CODE REVIEW

**Comment by nyospe** [comment]
@dkorolev @mzhurovich A few issues than came up with recent changes when building on Windows...

**Comment by dkorolev** [comment]
LGTM++, will merge from the proper keyboard and logged in GitHub in an
hour.

Quick question: won't operator= work as is? The type is templated, it won't
even try compiling what can not, or what am I missing?

Thanks!

On Monday, April 25, 2016, Nathan F Yospe <notifications@github.com> wrote:

> @dkorolev <https://github.com/dkorolev> @mzhurovich
> <https://github.com/mzhurovich> A few issues than came up with recent
> changes when building on Windows...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/C5T/Current/pull/478#issuecomment-214571012>
>


-- 
And, as always, have a nice day!
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Comment by nyospe** [comment]
It looks like it's an interpretation of the rule of 5...
The fact that a copy and move constructor are explicitly provided is blocking the implicit assignment operator.

**Comment by dkorolev** [comment]
Ah, right. Merging.

**Pull request merged**
