### PR TITLE
Travis Integration

### PR DESCRIPTION
**Pull request by dkorolev**
Hi Max,

I've configured Travis for Current: https://travis-ci.org/dkorolev/Current/builds.

(This is green on [`C5T/Current`](https://travis-ci.org/C5T/Current/pull_requests) -- D.K.)
[Build Status](https://travis-ci.org/dkorolev/Current)

It runs five jobs on every commit to every branch of `C5T/Current` or `dkorolev/Current` for now.

1. Run all tests on Linux with g++-5
2. Run all tests on Linux with clang++-3.6
3. Run `make check` on Linux with g++-5 and clang++-3.6
4. Run all tests on OS X, with native clang++
4. Run `make check` on OS X, with native clang++

The tests are run sequentially; the top-level `make test` was eating up too much RAM during compilation.

Moving forward, I think we'll have Travis build every commit to every branch of `C5T/Current`, and only commits to `travis*` branches of `{dkorolev,mzhurovich,...}/Current`.

Issues found and fixed in the meantime:

1. FnCAS: Uses the `Current` `Makefile` now, and I added `-ldl` into it.
2. Midichlorians' "App install/update time" on OS X. We used to test it's >= 2014, but Travis' CI image was ~2013. I moved the cutoff date back to 2001, to a round number of `1000000000000u` epoch milliseconds
3. Midichlorians' `std::atomic_size_t` for the number of events, and a spin lock on it was buggy: the `EXPECT_EQ` on the next line was only seeing four events instead of five `(*)`. I replaced it by a plain mutex, see the code. Uncertain what was causing the issue, and alarmed / curious whether it's affecting us anywhere else. **Edit**: Looks like a regular concurrency bug though, :fc: it's fixed in the latest commit of this PR.

Issues found and not fixed in the meantime:

1. Midichlorians compilation warnings on OS X. The code which returns a const reference from a lambda looks correct to me.
2. Karl's tests, both `EndToEndTest` and `KarlNotifiesUserObject` have stalled for 10+ minutes at least once during my ~40 runs. Well, at least we'll have it journaled now.

`(*)`

Garbage 1, from https://travis-ci.org/dkorolev/Current/jobs/141904893

```
test.cc:73: Failure
Expected: (event.app_install_time) > (1420000000000u), actual: 1385498816000 vs 1420000000000
test.cc:144: Failure
Value of: current::strings::Join(server.Messages(), ',')
  Actual: "0:Launch,1:GainedFocus[applicationDidBecomeActive],2:Identify[unit_test],5:CustomEvent1[source=SmokeTest,b=1,s=str,x=1]"
Expected: "0:Launch," "1:GainedFocus[applicationDidBecomeActive]," "2:Identify[unit_test]," "5:CustomEvent1[source=SmokeTest,b=1,s=str,x=1]," "15:LostFocus[applicationDidEnterBackground]"
Which is: "0:Launch,1:GainedFocus[applicationDidBecomeActive],2:Identify[unit_test],5:CustomEvent1[source=SmokeTest,b=1,s=str,x=1],15:LostFocus[applicationDidEnterBackground]"
[  FAILED  ] MidichloriansClient.iOSSmokeTest (173 ms)
```

Garbage 2, from https://travis-ci.org/dkorolev/Current/jobs/141907630

```
test.cc:149: Failure
Value of: current::strings::Join(std::vector<std::string>(msgs.begin(), msgs.begin() + 5), ',')
  Actual: "0:Launch,1:GainedFocus[applicationDidBecomeActive],2:Identify[unit_test],5:CustomEvent1[source=SmokeTest,b=1,s=str,x=1],!\x5\x9A\xFA\a\0p\xD5\x1F\x5\x9A\xFA\a\0\xA0\x2\0\x5|\xFF\x7F\0\0\xD0\xADQ\xA0\xA9\x7F\0\0\xE8\xADQ\xA0\xA9\x7F\0\0\xD0\xADQ\xA0\xA9\x7F\0\0py\x9FT\xFF\x7F\0\0\x80u\x9F\0\xFF\x7F\0\0hH]\x8B\xFF\x7F\0\0\xF1\0\0\0\0\0\0\0x\0\0\0\0\0\0\0 \xAEQ\xA0\xA9\x7F\0\0Wy\x9FT\xFF\x7F\0\0py\x9FT\xFF\x7F"
Expected: "0:Launch," "1:GainedFocus[applicationDidBecomeActive]," "2:Identify[unit_test]," "5:CustomEvent1[source=SmokeTest,b=1,s=str,x=1]," "15:LostFocus[applicationDidEnterBackground]"
Which is: "0:Launch,1:GainedFocus[applicationDidBecomeActive],2:Identify[unit_test],5:CustomEvent1[source=SmokeTest,b=1,s=str,x=1],15:LostFocus[applicationDidEnterBackground]"
```

PS: This was pain.

pain 1
pain 2

### CODE REVIEW

**Comment by mzhurovich** [comment]
Still don't quite get the "concurrency bug" in Midichlorians. How did the code result in garbage? Our HTTP is single-threaded, so `modify container` -> `increase atomic variable` sequence looks legit while waiting in a spin lock.

**Comment by mzhurovich** [comment]
And Midichlorians compilation warnings look like a bug in Clang - http://stackoverflow.com/questions/26744556/warning-returning-a-captured-reference-from-a-lambda.
My version (`Apple LLVM version 7.0.2 (clang-700.1.81)`) doesn't display any warnings for this part of the code (we have one for the deprecated `sendSynchronousRequest` though).

**Comment by dkorolev** [comment]
Confirmed clang on Travis issues the warning:

```
Dir: ./Bricks/strings
test.cc:707:14: warning: reference to stack memory associated with local variable 'foo' returned [-Wreturn-stack-address]
      return foo;
             ^~~
test.cc:709:14: warning: reference to stack memory associated with local variable 'bar' returned [-Wreturn-stack-address]
      return bar;
             ^~~
2 warnings generated.
```

**Comment by dkorolev** [comment]
And confirmed Travis is using clang++-3.5.

**Comment by dkorolev** [comment]
TODO(dkorolev): Figure out why this code with non-public constructor correctly fails in g++ on Linux, but passes on clang++ on OS X. https://travis-ci.org/C5T/Current/builds/142039675

Must be a preprocessor directive.

**Pull request merged**
