### PR TITLE
I f*cking had to re-create the `typesystem` dir to get rid of those case-insensitive warnings on Mac.

### PR DESCRIPTION
**Pull request by dkorolev**

### CODE REVIEW

**Comment by dkorolev** [comment]
Interestingly, to fully fix the issue I had to re-clone the repo. Just fast-forwarding didn't do the job.

@sompylasar, here's me openly stating git does suck. Only on a Mac though. Because Mac's file system sucks. Oh well.

**Comment by sompylasar** [comment]
I'd be surprised if this didn't kill the historical change tracking for these files (git blame). A two-commit rename (move) might have been a better idea.

**Comment by dkorolev** [comment]
I tried that. It didn't work.

**Comment by sompylasar** [comment]
I believe it did work, but you haven't re-cloned to see that.

**Pull request merged**
