### PR TITLE
Migrated to latest RapidJSON.

### PR DESCRIPTION
**Pull request by mzhurovich**
1. Added RapidJSON files and changes in Current in two separate commits.
2. Deprecated floating point test completely, since:
  * RapidJSON now outputs NaN's and Inf's as max type value;
  * Looks like output precision is not constant due to a new sophisticated conversion algorithm: http://www.cs.tufts.edu/~nr/cs257/archive/florian-loitsch/printf.pdf

### CODE REVIEW

**Comment by dkorolev** [comment]
Looking into. `Blocks/HTTP` tests failed from the 1st run.

**Comment by mzhurovich** [comment]
@dkorolev
One more thing. Custom files in '3rdparty/rapidjson':
* `version.h` with the info about the version of the files
* `streamwrapper.h` - new iostream wrapper based on original example.

**Comment by dkorolev** [comment]
Oh, let's put them into the README of that directory then.

**Comment by mzhurovich** [comment]
@dkorolev Looks like it works now :)
What did you mean exactly to put into 'README'?

**Comment by dkorolev** [comment]
Looking. Your comments about added/modified files. Perhaps rename `version.txt` into `README[.md`, and add the above comment there?

**Comment by dkorolev** [comment]
MERGING!

**Comment by mzhurovich** [comment]
Yay!

**Pull request merged**
