### PR TITLE
The top-level `make test` fix.

### PR DESCRIPTION
**Pull request by dkorolev**

### CODE REVIEW

**Comment by dkorolev** [comment]
@mzhurovich A very valid point is that `using namespace current` should not break anything in Current. We'll address it separately.

**Comment by dkorolev** [comment]
Notes:

1. The issue is with the macro expanding templated syntax as part of its arguments.
2. The issue is easy to reproduce by adding `using namespace current;` to the top of `RipCurrent/test.cc`
3. The top-level issue is easy to reproduce by adding `using namespace current;` to the top of `everything.cc` generated by the top-level `make test`.

I'll get there. Eventually.

**Comment by dkorolev** [comment]
And the top-level `make test` from this pull request does pass.

**Comment by mzhurovich** [comment]
@dkorolev 👍

**Pull request merged**
